### ISSUE TITLE
Top Font Outline Size and Top Font Outline Color not working as expected

### ISSUE THREAD

**Issue by ZeroCoolGOS** [MattsShack/Plex-Movie-Poster-Display#14]
Logging an issue with the:
- Top Font Outline Size
- Top Font Outline Color

Any changes set to these two fields are not being applied at runtime.

Testing still needs to be done for "Bottom" as well as for the "Coming Soon" sections as well.

System still defaults to the "Yellow" as part of the "Top Font Outline Color" no matter what value is set.

**Comment by MattsShack** [comment]
I tested the top and bottom text for Coming Soon and changes apply when changed.

**Comment by ZeroCoolGOS** [comment]
More documentation may want to be added.  Keeping the size less then 10% of the size will give the outline, anything more will overwrite the size and color.
