### ISSUE TITLE
Two Admins

### ISSUE THREAD

**Issue by Bboy486** [MattsShack/Plex-Movie-Poster-Display#33]
http://192.168.1.xx/admin.php
https://prnt.sc/101kf9y

http://192.168.1.xx/settings/login.php
https://prnt.sc/101kfpd

**Comment by ZeroCoolGOS** [comment]
We have yet to remove the legacy admin page. 

Since it has ￼diverged we should remove it soon. 

It was kept as backup as we where still validating the new admin pages.

**Comment by MattsShack** [comment]
Correct. The old admin page can be retired.  
@ZeroCoolGOS has done a great job on the new page and is where all the future development is being done.

**Comment by ZeroCoolGOS** [comment]
The original admin files have now been removed.

This ticket should now be able to be closed.
