### ISSUE TITLE
Scrolling Summary Bottom Text for Now Showing

### ISSUE THREAD

**Issue by titelies** [MattsShack/Plex-Movie-Poster-Display#39]
I have been using Matt's original PMPD work up til yesterday when I finally replaced my Pi 3 with a new Pi4 8GB cause I was dealing with swap memory and wifi issues. Images would stall and have to catch up all the time. Anyways, appreciate all the progress the Dev updates have made. One thing I have been used to is having scrolling text (upwards) in the Now Showing bottom text for movie Summary and the text wraps (doesn't currently wrap) into the vertical screen (screenshot link below). If I currently enable Common Configuration Bottom Scrolling Text that also scrolls the Coming Soon Bottom Text which version 2 didn't do and I'd prefer it not to do.  Greatly appreciate all the work on this beautiful project! https://i.imgur.com/dPGhOvr.jpg

**Comment by titelies** [comment]
Thanks for this wrap text scroll fix! Still investigating the look of the scroll, seems to pause/jitter sometimes, not sure if it's Pi WiFi issue on my new Pi4 8GB.

**Comment by ZeroCoolGOS** [comment]
I don't think it's your hardware.

It might be the JavaScript being used as I too have a jittering.

Depending on the amount of text and the speed that things are set.

So if you have the refresh to set for a short time and there is a lot of text then it could jump.  Also there is a pre pause when it first loads.  

I am not totally familiar with this piece of code so I don't know all the ins and outs yet. 

I will still try and see what can be done to make it smoother.

**Comment by titelies** [comment]
Thanks Geoff @ZeroCoolGOS sample video: https://i.imgur.com/RnXNVp7.mp4

**Comment by ZeroCoolGOS** [comment]
Interesting.  I saw something like that when I was testing but I thought I had fixed it. 

Can you also validate it has the same issue on your PC or phone?  Just want to check if it could be front end or back end.  

Also what TV make and model are you using?  It's got some nice clean lines.  Just what I'm looking for.

**Comment by titelies** [comment]
Tested on Brave browser on Linux and it has the same jitter effect.
TV depth is more than I would have liked but I was also trying to keep the costs down. However, I wanted the borders to be minimal and symmetrical... Sharp 50 LED 1080p Smart HDTV Roku TV https://www.bestbuy.com/site/sharp-50-class-led-1080p-smart-hdtv-roku-tv/4863102.p?skuId=4863102

**Comment by ZeroCoolGOS** [comment]
I still have not been able to recreate the jitter issue that is happening.
How often do you have the refresh set for?

**Comment by titelies** [comment]
@ZeroCoolGOS It's currently set at 5 seconds which is slower than the 3 seconds I used to use on PMPD2. What do you recommend Geoff?

**Comment by ZeroCoolGOS** [comment]
Well that is most likely the problem with the jittery.

The default timer is 30 seconds.

Try that and see if it fixes up the scrolling text.

**Comment by titelies** [comment]
@ZeroCoolGOS  Changed the transition time back to 30 secs. as recommended. Seemed to be better but still had an odd reset. 
https://i.imgur.com/p6y5CG3.mp4  Wonder if transition time for Coming Soon and Now Showing could be customized separately.  Now that I have changed it to 30 secs. the posters for Coming Soon don't show enough for a person that has a large Plex collection. Had to change it back to 5 secs.

**Comment by ZeroCoolGOS** [comment]
Interesting that it would jump mid time.

Yes.  I am splitting the transition time for Coming Soon and Now Showing.  I am targeting the PR for that sometime in the next day or two.

I will still try and keep an eye out for this scrolling issue and see if we can smooth it out in future builds.

**Comment by titelies** [comment]
Adding the separate transition times has solved the jitter issue for scrolling Now Showing Summary Text and I am also able to use Coming Soon with a quicker transition speed to show the many posters available on my Plex server. Thanks Geoff! @ZeroCoolGOS

**Comment by ZeroCoolGOS** [comment]
Good to hear.
