### ISSUE TITLE
Custom Font Top Text Alignment

### ISSUE THREAD

**Issue by titelies** [MattsShack/Plex-Movie-Poster-Display#42]
Really like the suggestion of the FamFonts site for custom fonts for use with PMPD and while many of the Movie font types show up as generic fonts some of my favorites like The Avengers, Predator, The Godfather, and Indiana Jones fonts look very attractive. It seems the area where the Top Text is located needs to be set for midline alignment (center vertical) if that's what it's called cause the text is centered horizontally but it does not center vertically and gets cut off even with much smaller font size choices. Issue applies to Coming Soon, Now Showing, and Custom Image Configuration. Bottom Text vertical and horizontal alignment seems to work really well on the 3 pages other than the Wrap Text that i also reported. Thank you again, hope I am able to help make PMPD a Flawless Victory!  https://i.imgur.com/NABadBM.jpg
https://i.imgur.com/YPgJxwt.jpg
https://i.imgur.com/RggN5QJ.jpg

**Comment by ZeroCoolGOS** [comment]
Interesting. 

It's something we can definitely look at post "rebrand" issue.

**Comment by titelies** [comment]
@ZeroCoolGOS  So, it looks like choosing a different custom font solves this issue. Using the Blade Runner font aligns properly

**Comment by ZeroCoolGOS** [comment]
Cool.  Ya, its kinda hit and miss with custom fonts sometimes.  Its all about what the bounds are and how to find the center and scale properly.
