### ISSUE TITLE
Coming Soon - Show Media: ALL - Not Displaying TV Show Posters

### ISSUE THREAD

**Issue by titelies** [MattsShack/Plex-Movie-Poster-Display#51]
FYI Geoff when the Coming Soon Show Media dropdown is selected to ALL, a blank (black) poster will appear no matter whether the setting is Series or Season. If I remove the number representing my TV Shows library in the Plex Configuration, then the blank poster does not appear any longer.

**Comment by titelies** [comment]
Ah, just noticed if I select Episode from the dropdown, the Season poster appear. Switch it back to Series or Season and it provides a blank image.

**Comment by ZeroCoolGOS** [comment]
Hmm. 

Well what I have set up is if the the episode poster does not exist then it will try the season, then the series. 

I will add some logging to capture this fail over.

Does it happen on all shows or is it random?

If it's random.  Can you check your plex server and validate that all your posters are showing correctly there?

Some of my TV shows don't set the posters correctly so I have to manually tweak them. 

I have found TV shows have been a bit more tricky then movies.  Music even more so.

There is still some more work to do to make TV shows more useful.

**Comment by titelies** [comment]
The 3 Display TV Show settings work correctly for Recently Added and Newest. However for Unwatched and All choices, TV Show posters are blank if I choose Season or Series. If I select Episode, then it will show the Series poster and not Episode images. I am OCD about my Plex library posters/backgrounds so all TV Show series posters are different from the Season ones, which have the Season One, Two labeled on each of the posters, and Episode posters are horizontal images from the episode, not a poster. Hope this helps.

**Comment by ZeroCoolGOS** [comment]
Sounds good. 

I will give that combo a try and hopefully recreate the issue your having and try and address it soon. 

They way that Plex provides the data via API changes between types when it comes to tv shows.

**Comment by ZeroCoolGOS** [comment]
I have been able to recreate the issue and I have identified the problem.

So now when running in "All" or "Unwatched" there should not be any more blank posters, but get the Series poster.

When you have selected either "All" or" Unwatched" of these the "Episode/Season/Series" is no longer usable as this extra metadata is not available from the PLEX API.

Fix should be ready in build v2.10.2 sometime this weekend or early next week

**Comment by titelies** [comment]
Amazed by how quickly you return with a solution! KUDOS!

**Comment by titelies** [comment]
It's so great to finally see Plex posters that I have never seen before on my PMPDisplay TV for over 4 years now!

**Comment by ZeroCoolGOS** [comment]
No worries.

I am looking to build my TV display this summer.  But in the mean time I am enjoying working on this project.  Its a pretty cool application that Matt wrote.

**Comment by titelies** [comment]
Great @ZeroCoolGOS ! I would suggest noting that if All or Unwatched are selected, only Series posters will display. Eitther under Show Media or added to the "Display TV Show information from" note. Just so there's no confusion for others as to why Series posters are displaying when they have selected Season for example.

**Comment by ZeroCoolGOS** [comment]
I will update the comments to reflect that.

**Comment by titelies** [comment]
Looks good!
