### ISSUE TITLE
Where is the admin.php in the dev branch?  Trying to update from a previous DEV version several months old and i find no admin.php any longer

### ISSUE THREAD

**Issue by jeffreyswiggins** [MattsShack/Plex-Movie-Poster-Display#52]
Where is the admin.php in the dev branch?  Trying to update from a previous DEV version several months old and i find no admin.php any longer

**Comment by titelies** [comment]
Personally, I grabbed a new Micro SD card for my Pi and started from scratch. PMPD has evolved quite a bit. There's no admin.php page any longer in 2.10. Pages have been revised, new pages, new directories from what I can tell from the previous PMPD versions. https://github.com/MattsShack/Plex-Movie-Poster-Display/issues/33

**Comment by MattsShack** [comment]
http://<ip_of_raspberry_pi>/settings/login.php is the new login page.

**Comment by jeffreyswiggins** [comment]
okay thanks..... is there a new DISPLAY page as well... all i get now is the blank page with a X button on the top corner when i go to http://<ip_of_raspberry_pi>/.  In the version i have working that is where it was to go and what your documentation said.  Read thru the /docs folder and it looks like that hasnt been updated

**Comment by ZeroCoolGOS** [comment]
No, there is not a new display page.  Just the admin page has been updated. 

Could you please attach a screenshot of the issue your seeing?  I have not seen that issue of having an X on the display page.

Most of the documentation should be up to date.  What part of the documentation is out of date and we will look at making sure it's updated.

**Comment by ZeroCoolGOS** [comment]
I have identified a few small out of date items within the documentation and will have them resolved in the next update.

**Comment by jeffreyswiggins** [comment]
Okay...  I went out of town until Sunday so will try to screen capture the X button when I get back

Jeffrey Wiggins
(918) 609-5934 - Home
(918) 809-1398 - Cell
***@***.***

**Comment by ZeroCoolGOS** [comment]
@jeffreyswiggins 

I know you where out of town this weekend.  When you return and have a chance, can you please provide an image of the issue you where having?

I have ran into a similar blank issue on a machine that was out of date and have made a few modifications to help address the issue, but I did also find out that some of my dependencies where either missing or out of date.   So if  you pull the latest build (2.10.4) and still have the issue I would recommend to update the dependencies to see if that helps your issue.

The one I found to have the issue was the php-curl package was missing on my older system.

**Comment by jeffreyswiggins** [comment]
So first I looked a the new documentation after I pulled the 2.10.4 and noticed your photos show a nice almost PLEX themed interface at the http://ipaddress/settings.login.php and i get this  After setting my plex server and client configuration in it I get this at the main http://ipaddress/Maybe I have out of date PHP or missing something but here is the PHP I have installed that works the old master branch  Sent from Mail for Windows 10 From: Geoff S.Sent: Tuesday, March 16, 2021 3:48 PMTo: MattsShack/Plex-Movie-Poster-DisplayCc: jwiggins10471; MentionSubject: Re: [MattsShack/Plex-Movie-Poster-Display] Where is the admin.php in the dev branch? Trying to update from a previous DEV version several months old and i find no admin.php any longer ***@***.***I know you where out of town this weekend. When you return and have a chance, can you please provide an image of the issue you where having?I have ran into a similar blank issue on a machine that was out of date and have made a few modifications to help address the issue, but I did also find out that some of my dependencies where either missing or out of date. So if you pull the latest build (2.10.4) and still have the issue I would recommend to update the dependencies to see if that helps your issue.The one I found to have the issue was the php-curl package was missing on my older system.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avast.com

**Comment by ZeroCoolGOS** [comment]
@jeffreyswiggins 

Yes, the new admin interface does look similar to the plex admin interface, but we have been changing out the colors and changing the design as we cannot use some of the same design elements.

If you have attached any images to your last post, the are not showing up.

The old "master" branch has older dependencies and they have been updated in the dev branch, and a few more should be added as well.

In the future we plan to have an "upgrade" script that will run an update to install the update and install components as well as copy the files to the var/www/html folder.  But for the time being its still a manual process.

**Comment by jeffreyswiggins** [comment]
So I am doing the curl command to pull you entire dev branch and then copying that over to /var/www/html/pmpd-dev/ folder which is my test folder.  Then I set the permissions and ownership per your instructions.  End result is that funky white config/login and X pages.


Jeffrey Wiggins
(918) 609-5934 - Home
(918) 809-1398 - Cell
***@***.***

**Comment by ZeroCoolGOS** [comment]
Interesting.  I had not tried to use it in a subdirector before.

I have tested it out and copying the files to the subfolder seems to work correctly.

I did get a white screen after I logged in, but then once I refreshed my permissions and did a page refresh things displayed fine.

I am not seeing the funky white config/login and X pages you mentioned.

**Comment by jeffreyswiggins** [comment]
I will tar up my current master and then wipe and replace it with this and see if being in that folder fixes it.  Does it need to be in the Plex-Movie-Poster-Display named folder?  I shortened that to pmpd in my world cause it was a lot to type....

Jeffrey Wiggins
(918) 609-5934 - Home
(918) 809-1398 - Cell
***@***.***

**Comment by ZeroCoolGOS** [comment]
No it does not.

I always have it in my root folder (var/www/html) so the only time I have it in "Plex-Movie-Poster-Display" is in my git folder.

**Comment by jeffreyswiggins** [comment]
So attached are the photos i tried to put in earlier of the login.php , the main page, and then the php version page

![login php](https://user-images.githubusercontent.com/29712548/111394467-cabd2600-8688-11eb-8326-ea0b266474b9.png)
![main page](https://user-images.githubusercontent.com/29712548/111394469-cabd2600-8688-11eb-9ab1-28c552a3416f.png)
![php](https://user-images.githubusercontent.com/29712548/111394471-cb55bc80-8688-11eb-80c6-352d9f9f9333.png)

**Comment by ZeroCoolGOS** [comment]
interesting, that looks like its a CSS issue, as it should be loading that file.

can you confirm that you have the following two files:
"var/www/html/pmpd-dev/assets/plexmovieposter/css/SettingsStyle.css"
"var/www/html/pmpd-dev/assets/plexmovieposter/css/DisplayStyle.css"

**Comment by jeffreyswiggins** [comment]
Yes. i have those.... so i just tar'd and archived up my files in /var/www/html/ and then wiped the folder clean.  I put a new set of the 2.10.4 code directly in /var/www/html/ and did the perms and ownership and viola the CSS problem seems to be fixed as the page looks like it should and is coloful.... will start testing adding my configurations and then see if it works.... guess a subfolder is a no go or at least named **pmpd-dev** doesnt work

**Comment by ZeroCoolGOS** [comment]
If you want to write up a feature request for that then we can put it in the backlog for something to look into.

**Comment by jeffreyswiggins** [comment]
So after testing its works as expected for COMING SOON and NOW SHOWING....... where do i get font files from? Just standard font files downloaded from google that i upload to it?

**Comment by ZeroCoolGOS** [comment]
I usually get it from https://famfonts.com/

but ya, you can google and download.  If its a single file it currently only supports ttf files. but if you upload in a zip file then any of the standard webfonts should work.

I you use the link I provided you get a zip file so you can just use that to upload the font you like.

**Comment by jeffreyswiggins** [comment]
interesting.... downloaded the Mandalorian as it was teh first on their page i saw i liked... uploaded and the page went white and is just sitting for over a minute no update or result.  I uploaded the zip file.... do i have to restart something afterwards?

**Comment by ZeroCoolGOS** [comment]
There should not be anything that you need to restart.

when you upload the font it should unzip it and show a sample on the font page.

**Comment by ZeroCoolGOS** [comment]
Did you install php-zip?

**Comment by jeffreyswiggins** [comment]
no i did not.....

**Comment by ZeroCoolGOS** [comment]
Then that would be the problem.  The Font system requires php-zip to be installed as a dependency.

**Comment by jeffreyswiggins** [comment]
whoop there it is......
