### ISSUE TITLE
Enhancement: Multiple IP Clients for Now Showing

### ISSUE THREAD

**Issue by titelies** [MattsShack/Plex-Movie-Poster-Display#59]
I have always hoped that one day PMPD would work with more than one Client IP address for Now Showing. It's very rare that PLEX is being used at the same time in my household. It would be great to have the ability to add multiple client IP Addresses (whether separated by comma or semicolon) so that if anyone of those devices were playing something on Plex than Now Showing would display that poster.  However, if Plex were being used on multiple clients, then maybe the order of the IP addresses would control which poster is displaying on Now Showing, example:  192.168.1.100, 192.168.1.50, 192.168.1.90 are all playing Plex Movies, since .100 is 1st in the row, displays on Now Showing, once Stopped/Ended, then .50 etc....

**Comment by ZeroCoolGOS** [comment]
This is interesting, but could be tricky depending on what data is passed as part of the API.

I am not sure if it supported multiple clients in the past.  @MattsShack  could shed some light on that.

The only thing that is restricted is the field length from the changes I made.  We can look at expanding that field and trying it out.

I have a feeling that would not be based on IP but based on latest playing client.  But could still use some research.

**Comment by MattsShack** [comment]
The system was not designed to be used with multiple clients. The feature has been requested a few time, however @ZeroCoolGOS is correct... it is tricky... Maybe sometime in the future :).

**Comment by titelies** [comment]
Pretty sure all those requests were mine... LOL! Thanks again Matt, looking forward to it one day!
![bitmoji](https://sdk.bitmoji.com/render/panel/7e19c9c7-b063-4211-a5e5-e757ac801a00-9c976e62-8da9-4ee7-9e9f-f2753c26292e-v1.png?transparent=1&palette=1&width=246)

**Comment by ZeroCoolGOS** [comment]
@titelies 
In the meantime you could run multiple instances of the site, one dedicated per client.

**Comment by titelies** [comment]
Jaw-Dropped for this!!! KUDOS, works great! Successfully tested. Newest movie to be played from the 3 devices is what gets displayed on Now Showing but I'm fine with that! Huge thanks Geoff, I've been waiting for this feature for a long time!

**Comment by ZeroCoolGOS** [comment]
Glad it its working for you and you did not have to much of and issue upgrading to 2.11.

I have not fully worked out how the multiple clients works and how the "Client Name" comes into play.  In the future maybe we could add "Client Name" as a 5th option for display if that is something that could be useful.

Still need to do more research.
