### ISSUE TITLE
SSL Support for Plex Server

### ISSUE THREAD

**Issue by mhankosky** [MattsShack/Plex-Movie-Poster-Display#7]
My server is set up to only allow SSL (HTTPS) for plex connections.  

I attempted to edit the lines of index.php to https, however i can not get it to connect. I get just a black screen. 

I verified my Token manually and it works fine.
 
I also tested the Un-watched url and it works fine as well with https (https://LocalIP5:32400/library/sections/1/unwatched?X-Plex-Token=SSSSSSSSSSSSSSSSSSSSSSS)

**Comment by mhankosky** [comment]
Just an update.  I was able to get it working by making the following changes:

1 - In GetData.php, Change all instances of HTTP:// to HTTPS://
2 - Instead of using the local IP, use the Plex Direct DNS name (For a valid SSL)   - To get this, Simply follow the same instructions for getting your Plex Token, but copy the URL It will look like **IP-IP-IP-IP.averylograndomstring.plex.dire**ct  By using that in the IP line, It works fine.

Suggestion:

Add a option in the admin to select HTTP or HTTPS for the config file.

**Comment by ZeroCoolGOS** [comment]
@mhankosky 
I am working on an update to support SSL as well as the standard system and hope to have it as a PR to @MattsShack by the end of the Week/Month/Year :D

I have a working version, I am now trying to figure out is how to document where you can find the 'plex.direct' url as its not documented in the plex support documents very well.

**Comment by ZeroCoolGOS** [comment]
@mhankosky 
This feature should now be available for you from the dev branch as the PR has now been accepted.

**Comment by MattsShack** [comment]
Tested and this works. Thank you :)

**Comment by ZeroCoolGOS** [comment]
@MattsShack  This issue should be able to be closed.

**Comment by titelies** [comment]
Can someone assist me with setting up HTTPS to work successfully for PMPD... I have Enable Plex SSL connection enabled in the PMPD Plex Configuration setting and I also have the IP-IP-IP-IP.MYCERTAINAINFO.plex.direct in the Plex Server Direct address. On the Plex Media Server network settings I have Secure connections set to: Preferred. However, when I change try to access the PMPD posters from the https://192.168.1.100/index.php link, it says the site can't be reached, only accessible with http://  
Any advice would be greatly appreciated.
