### ISSUE TITLE
PMPD Pop-up Window with "S" Key

### ISSUE THREAD

**Issue by titelies** [MattsShack/Plex-Movie-Poster-Display#70]
I recently learned by accident that if I click on the "s" key on my keyboard, a NGINX pop-up window appears. I wonder if that pop-up window can be used for another reason such as metadata info or anything else that someone feels would be worthwhile... Just a thought! https://i.imgur.com/6K3Yr1u.png

**Comment by ZeroCoolGOS** [comment]
I remember seeing something in the code about that.  

I will look into that today and see what is going on.

**Comment by ZeroCoolGOS** [comment]
I have identified the issue with the 'S' option and will have an update for it in 2.11.3.

The reason behind it was to have a popup of the 'admin' page but now I have remapped it to the settings page for now.

In the future we could look at adding different hidden keys is requested.

**Comment by titelies** [comment]
Love the new feature @ZeroCoolGOS

**Comment by MattsShack** [comment]
Nice addition.

**Comment by ZeroCoolGOS** [comment]
> Nice addition.

@MattsShack 

Lol. Ya. It's a nice feature. You wrote it. I just fixed it with the change to the setting page. 😄
