### ISSUE TITLE
Refresh All Metadata for Plex Sections

### ISSUE THREAD

**Issue by titelies** [MattsShack/Plex-Movie-Poster-Display#71]
So, now that I have been able to disable the 24 hr Expiration of the Cache files for Posters and Art, I noticed that the highest my cache stats would get was 1565 across the 8 sections that I have entered in the Plex Movie Sections field separated by commas. It wasn't until I did a Refresh All Metadata of each of the 8 sections, that now the stats number has increased to 1777 which is a more accurate number of the total of the 8 sections. Hope this is helpful to someone else.

**Comment by ZeroCoolGOS** [comment]
This could be that Plex has duplicated some of the IDs for some media. I have seen that.

All we do is just query Plex and use the data that it provides.  If the metadata is out of sync on the Plex Server side, there is nothing we can do.

Other then the cache number, are you getting miss matched display images?

**Comment by titelies** [comment]
Nope, all is good. And the stats number now keeps increasing as expected and I am seeing posters that I have not seen before. Seems like if you add a new section number to the Plex Sections on PMPD, its a good idea to run a Refresh All Metadata for that section on Plex.
