### ISSUE TITLE
Coming Soon All or Unwatched not displaying Series Posters Anymore

### ISSUE THREAD

**Issue by titelies** [MattsShack/Plex-Movie-Poster-Display#79]
Not sure if it was a Plex Media Server update or PMPD 2.11.6 but Coming Soon... All or Unwatched no longer showing TV Show Series posters, just blank where the image should be while showing the Top and Bottom Titles.

**Comment by ZeroCoolGOS** [comment]
That is odd. 

2.11.6 should not have caused anything like that.  

I will test it today.  But I have not updated my Plex server recently.

**Comment by ZeroCoolGOS** [comment]
Ok.

I can recreate the error and kind of have an idea as to what is happening so I will try and make a fix this evening or tomorrow.

**Comment by titelies** [comment]
Thanks for the fix @ZeroCoolGOS
