### ISSUE TITLE
Raspberry Pi Updates - Back to Welcome to nginx page 

### ISSUE THREAD

**Issue by titelies** [MattsShack/Plex-Movie-Poster-Display#90]
Ran updates on my Raspberry Pi and now this morning after turning on TV display, it's back to the Welcome to nginx page and displaying that further configuration is required... 🤦‍♂️ Any help would be greatly appreciated!
[PXL_20210531_150118346.jpg](https://user-images.githubusercontent.com/16294530/120212283-c6bc9100-c1ff-11eb-89d3-2e304e9428fb.jpg)

**Comment by titelies** [comment]
So, I just realized that my laptop is still displaying the PMPD posters if I go to the web address... thinking one of the updates must have changed my kiosk setup. Will have to look into it when I get some time.

**Comment by titelies** [comment]
Had to edit the following:
sudo nano /etc/xdg/lxsession/LXDE-pi/autostart

Needed to revise the address: (previously was using http://localhost)
had to change it to http://192.168.1.1/index.php

/usr/bin/chromium-browser --kiosk  --disable-restore-session-state http://192.168.1.1/index.php
Now, it's working again, if I leave it http://192.168.1.1 (without the index.php) it will go to the Welcome to the nginx page.

**Comment by MattsShack** [comment]
Thank you @titelies . I updated the site(s).
