### ISSUE TITLE
Poster Statistics incrementing, permanent blank screen regardless.

### ISSUE THREAD

**Issue by Jacksaur** [MattsShack/Plex-Movie-Poster-Display#91]
Installed the latest Dev version this morning on a fresh Pi Zero W, and whilst the server itself seems to be running fine, I can access all settings and the Poster statistic constantly counts up, nothing is ever displayed. No text, no posters, neither when the server is idle or currently playing media.
I've messed around with various settings whilst reading through issues here, setting fullscreen, checking my Plex Movie Sections sources, Token, etc. Nothing has had any effect thus far.
Following as another user mentioned, I tried php -f getData.php and got this warning:
PHP Warning:  file_put_contents(/var/www/html/cache/logs/getPoster.log): failed to open stream: Permission denied in /var/www/html/assets/plexmovieposter/tools.php on line 75
I have ran the chmod and chown commands mentioned in the installation guide.

I'm afraid I'm entirely new to all of this, so apologies if I'm missing something obvious here.

**Comment by 1upmushroom** [comment]
Same exact issue, followed directions to a T.

**Comment by TATUMTOT** [comment]
Same issue.

**Comment by TATUMTOT** [comment]
> Same issue.

Also don't see any Cached Data being placed from the plex server.

**Comment by ZeroCoolGOS** [comment]
Would it be possible for you to upload your config files (sans token) so I can look over the config files to see if there is an issue from that end.

Also please send a copy of the log file for review. 

Are you using a PiZero for just the server or display? Have you tried to connect to it from a different system and ￼browser?

**Comment by TATUMTOT** [comment]
Using a Pi4 for both server and client at this time. Was going to put three or 4 of these up in the theater room.

Just saw this in the backup config. 
   $plexServerSSL = '1'; // Default: FALSE
This probably should be True and not 1 but i'm not sure going to swap SD card and try again with this manually changed to True. 

// Plex Configuration
  $plexServer = '10.0.5.100';
  $plexServerDirect = '';
  $plexToken = '';
  $plexServerMovieSection = '1';
  $plexServerSSL = '1'; // Default: FALSE
  $plexClient = '10.0.5.103';
  $plexClientName = '';






<?php
  // PMPD Configuration
  $pmpConfigVersion = '2.10.7';
  $pmpUsername = 'admin';
  $pmpPassword = 'password1';
  $pmpClearImageCache = 'Yes'; // Default: Yes
  // $pmpImageSpeed = ''; // Default: 30 (Seconds)

  // Cache Configuration
  $cacheEnabled = '1'; // Default: TRUE
  $pmpPosterDir = 'cache/posters/'; // Default: cache/posters/
  $pmpPosterDir_24hExp = '1'; // Default: TRUE
  $pmpArtDir = 'cache/art/'; // Default: cache/art/
  $pmpArtDir_24hExp = '1'; // Default: TRUE
  $pmpCustomDir = 'cache/custom/'; // Default: cache/custom/
  $pmpCustomDir_24hExp = ''; // Default: FALSE
  $pmpFontDir = 'cache/fonts/'; // Default: cache/fonts/
  $pmpFontDir_24hExp = ''; // Default: FALSE
  $pmpLogDir = 'cache/logs/'; // Default: cache/logs/
  $pmpLogDir_24hExp = ''; // Default: FALSE

  // Plex Configuration
  $plexServer = '10.0.5.100';
  $plexServerDirect = '';
  $plexToken = '';
  $plexServerMovieSection = '1';
  $plexServerSSL = '1'; // Default: FALSE
  $plexClient = '10.0.5.103';
  $plexClientName = '';

  // Custom Image Configuration
  $customBackgroundArt = ''; // Default: FALSE
  $customFullScreenArt = ''; // Default: FALSE
  $customRefreshSpeed = '30'; // Default: 30 (Seconds)
  $customImageEnabled = 'Disabled'; // Default: Disabled
  $customImage = '';

  // Custom Image Configuration - Top Settings
  $customTopText = '';
  $customTopFontSize = '55'; // Default: 55 (px)
  $customTopFontColor = '#FFFF00'; // Default: #FFFF00 (Yellow)
  $customTopFontOutlineSize = '0'; // Default: 0 (px)
  $customTopFontOutlineColor = '#FFFF00'; // Default: #FFFF00 (Yellow)
  $customTopFontEnabled = ''; // Default: FALSE
  $customTopFontID = 'None'; // Default: None

  // Custom Image Configuration - Bottom Settings
  $customBottomText = '';
  $customBottomFontSize = '25'; // Default: 25 (px)
  $customBottomFontColor = '#FFFFFF'; // Default: #FFFFFF (White)
  $customBottomFontOutlineSize = '0'; // Default: 0 (px)
  $customBottomFontOutlineColor = '#FFFFFF'; // Default: #FFFFFF (White)
  $customBottomFontEnabled = ''; // Default: FALSE
  $customBottomFontID = 'None'; // Default: None

  // Coming Soon Configuration
  $comingSoonBackgroundArt = ''; // Default: FALSE
  $comingSoonFullScreenArt = ''; // Default: FALSE
  $comingSoonRefreshSpeed = '30'; // Default: 30 (Seconds)
  $comingSoonShowTVThumb = 'series'; // Default: series
  $comingSoonShowSelection = 'unwatched'; // Default: unwatched
  // $showComingSoonInfo = ''; // Default: FALSE

  // Coming Soon Configuration - Top Settings
  $comingSoonTop = 'custom'; // Default: custom (title/summary/tagline/custom)
  $comingSoonTopText = 'COMING SOON20';
  $comingSoonTopFontSize = '55'; // Default: 55 (px)
  $comingSoonTopFontColor = '#FFFF00'; // Default: #FFFF00 (Yellow)
  $comingSoonTopFontOutlineSize = '0'; // Default: 0 (px)
  $comingSoonTopFontOutlineColor = '#FFFF00'; // Default: #FFFF00 (Yellow)
  $comingSoonTopFontEnabled = ''; // Default: FALSE
  $comingSoonTopFontID = 'None'; // Default: None
  $comingSoonTopAutoScale = ''; // Default: FALSE

  // Coming Soon Configuration - Bottom Settings
  $comingSoonBottom = 'custom'; // Default: custom (title/summary/tagline/presented/custom)
  $comingSoonBottomText = 'www.mattsshack.0100';
  $comingSoonBottomFontSize = '25'; // Default: 25 (px)
  $comingSoonBottomFontColor = '#FFFFFF'; // Default: #FFFFFF (White)
  $comingSoonBottomFontOutlineSize = '0'; // Default: 0 (px)
  $comingSoonBottomFontOutlineColor = '#FFFFFF'; // Default: #FFFFFF (White)
  $comingSoonBottomFontEnabled = ''; // Default: FALSE
  $comingSoonBottomFontID = 'None'; // Default: None
  $comingSoonBottomAutoScale = ''; // Default: FALSE
  $comingSoonBottomScroll = 'Disabled'; // Default: Disabled

  // Now Showing Configuration
  $nowShowingBackgroundArt = ''; // Default: FALSE
  $nowShowingFullScreenArt = ''; // Default: FALSE
  $nowShowingRefreshSpeed = '30'; // Default: 30 (Seconds)
  $nowShowingShowTVThumb = 'series'; // Default: series
  $pmpDisplayProgress = 'Enabled'; // Default: Disabled
  $pmpDisplayProgressSize = '5'; // Default: 5 (px)
  $pmpDisplayProgressColor = '#FFFF00'; // Default: #FFFF00 (Yellow)

  // Now Showing Configuration - Top Settings
  $nowShowingTop = 'custom'; // Default: custom (title/summary/tagline/progessinfo/custom)
  $nowShowingTopText = 'NOW SHOWING';
  $nowShowingTopFontSize = '55'; // Default: 55 (px)
  $nowShowingTopFontColor = '#FFFF00'; // Default: #FFFF00 (Yellow)
  $nowShowingTopFontOutlineSize = '0'; // Default: 0 (px)
  $nowShowingTopFontOutlineColor = '#FFFF00'; // Default: #FFFF00 (Yellow)
  $nowShowingTopFontEnabled = ''; // Default: FALSE
  $nowShowingTopFontID = 'None'; // Default: None
  $nowShowingTopAutoScale = ''; // Default: FALSE

  // Now Showing Configuration - Bottom Settings
  $nowShowingBottom = 'title'; // Default: title (title/summary/tagline/presented/custom)
  $nowShowingBottomText = '';
  $nowShowingBottomFontSize = '25'; // Default: 25 (px)
  $nowShowingBottomFontColor = '#FFFFFF'; // Default: #FFFFFF (White)
  $nowShowingBottomFontOutlineSize = '0'; // Default: 0 (px)
  $nowShowingBottomFontOutlineColor = '#FFFFFF'; // Default: #FFFFFF (White)
  $nowShowingBottomFontEnabled = ''; // Default: FALSE
  $nowShowingBottomFontID = 'None'; // Default: None
  $nowShowingBottomAutoScale = ''; // Default: FALSE
  $nowShowingBottomScroll = 'Disabled'; // Default: Disabled

  // Misc Configuration
  $pmpDisplayClock = 'Disabled'; // Default: Disabled (FUTURE)
  // $pmpBottomScroll = ''; // Default: Disabled
  $pmpBottomScrollSpeed = '1'; // Default: 1 (FUTURE)
?>

**Comment by TATUMTOT** [comment]
<?php
  // PMPD Configuration
  $pmpConfigVersion = '2.10.7';
  $pmpUsername = 'admin';
  $pmpPassword = 'password1';
  $pmpClearImageCache = 'Yes'; // Default: Yes
  // $pmpImageSpeed = ''; // Default: 30 (Seconds)

  // Cache Configuration
  $cacheEnabled = '1'; // Default: TRUE
  $pmpPosterDir = 'cache/posters/'; // Default: cache/posters/
  $pmpPosterDir_24hExp = '1'; // Default: TRUE
  $pmpArtDir = 'cache/art/'; // Default: cache/art/
  $pmpArtDir_24hExp = '1'; // Default: TRUE
  $pmpCustomDir = 'cache/custom/'; // Default: cache/custom/
  $pmpCustomDir_24hExp = ''; // Default: FALSE
  $pmpFontDir = 'cache/fonts/'; // Default: cache/fonts/
  $pmpFontDir_24hExp = ''; // Default: FALSE
  $pmpLogDir = 'cache/logs/'; // Default: cache/logs/
  $pmpLogDir_24hExp = ''; // Default: FALSE

  // Plex Configuration
  $plexServer = '10.0.5.100';
  $plexServerDirect = '10-0-5-100.2asdfasdcasdc.plex.direct:32400';
  $plexToken = '';
  $plexServerMovieSection = '1';
  $plexServerSSL = 'True'; // Default: FALSE
  $plexClient = '10.0.5.103';
  $plexClientName = '';

  // Custom Image Configuration
  $customBackgroundArt = ''; // Default: FALSE
  $customFullScreenArt = ''; // Default: FALSE
  $customRefreshSpeed = '30'; // Default: 30 (Seconds)
  $customImageEnabled = 'Disabled'; // Default: Disabled
  $customImage = '';

  // Custom Image Configuration - Top Settings
  $customTopText = '';
  $customTopFontSize = '55'; // Default: 55 (px)
  $customTopFontColor = '#FFFF00'; // Default: #FFFF00 (Yellow)
  $customTopFontOutlineSize = '0'; // Default: 0 (px)
  $customTopFontOutlineColor = '#FFFF00'; // Default: #FFFF00 (Yellow)
  $customTopFontEnabled = ''; // Default: FALSE
  $customTopFontID = 'None'; // Default: None

  // Custom Image Configuration - Bottom Settings
  $customBottomText = '';
  $customBottomFontSize = '25'; // Default: 25 (px)
  $customBottomFontColor = '#FFFFFF'; // Default: #FFFFFF (White)
  $customBottomFontOutlineSize = '0'; // Default: 0 (px)
  $customBottomFontOutlineColor = '#FFFFFF'; // Default: #FFFFFF (White)
  $customBottomFontEnabled = ''; // Default: FALSE
  $customBottomFontID = 'None'; // Default: None

  // Coming Soon Configuration
  $comingSoonBackgroundArt = ''; // Default: FALSE
  $comingSoonFullScreenArt = ''; // Default: FALSE
  $comingSoonRefreshSpeed = '30'; // Default: 30 (Seconds)
  $comingSoonShowTVThumb = 'series'; // Default: series
  $comingSoonShowSelection = 'unwatched'; // Default: unwatched
  // $showComingSoonInfo = ''; // Default: FALSE

  // Coming Soon Configuration - Top Settings
  $comingSoonTop = 'custom'; // Default: custom (title/summary/tagline/custom)
  $comingSoonTopText = 'COMING SOON';
  $comingSoonTopFontSize = '55'; // Default: 55 (px)
  $comingSoonTopFontColor = '#FFFF00'; // Default: #FFFF00 (Yellow)
  $comingSoonTopFontOutlineSize = '0'; // Default: 0 (px)
  $comingSoonTopFontOutlineColor = '#FFFF00'; // Default: #FFFF00 (Yellow)
  $comingSoonTopFontEnabled = ''; // Default: FALSE
  $comingSoonTopFontID = 'None'; // Default: None
  $comingSoonTopAutoScale = ''; // Default: FALSE

  // Coming Soon Configuration - Bottom Settings
  $comingSoonBottom = 'custom'; // Default: custom (title/summary/tagline/presented/custom)
  $comingSoonBottomText = 'www.mattsshack.com';
  $comingSoonBottomFontSize = '25'; // Default: 25 (px)
  $comingSoonBottomFontColor = '#FFFFFF'; // Default: #FFFFFF (White)
  $comingSoonBottomFontOutlineSize = '0'; // Default: 0 (px)
  $comingSoonBottomFontOutlineColor = '#FFFFFF'; // Default: #FFFFFF (White)
  $comingSoonBottomFontEnabled = ''; // Default: FALSE
  $comingSoonBottomFontID = 'None'; // Default: None
  $comingSoonBottomAutoScale = ''; // Default: FALSE
  $comingSoonBottomScroll = 'Disabled'; // Default: Disabled

  // Now Showing Configuration
  $nowShowingBackgroundArt = ''; // Default: FALSE
  $nowShowingFullScreenArt = ''; // Default: FALSE
  $nowShowingRefreshSpeed = '30'; // Default: 30 (Seconds)
  $nowShowingShowTVThumb = 'series'; // Default: series
  $pmpDisplayProgress = 'Disabled'; // Default: Disabled
  $pmpDisplayProgressSize = '5'; // Default: 5 (px)
  $pmpDisplayProgressColor = '#FFFF00'; // Default: #FFFF00 (Yellow)

  // Now Showing Configuration - Top Settings
  $nowShowingTop = 'custom'; // Default: custom (title/summary/tagline/progessinfo/custom)
  $nowShowingTopText = 'NOW SHOWING';
  $nowShowingTopFontSize = '55'; // Default: 55 (px)
  $nowShowingTopFontColor = '#FFFF00'; // Default: #FFFF00 (Yellow)
  $nowShowingTopFontOutlineSize = '0'; // Default: 0 (px)
  $nowShowingTopFontOutlineColor = '#FFFF00'; // Default: #FFFF00 (Yellow)
  $nowShowingTopFontEnabled = ''; // Default: FALSE
  $nowShowingTopFontID = 'None'; // Default: None
  $nowShowingTopAutoScale = ''; // Default: FALSE

  // Now Showing Configuration - Bottom Settings
  $nowShowingBottom = 'title'; // Default: title (title/summary/tagline/presented/custom)
  $nowShowingBottomText = '';
  $nowShowingBottomFontSize = '25'; // Default: 25 (px)
  $nowShowingBottomFontColor = '#FFFFFF'; // Default: #FFFFFF (White)
  $nowShowingBottomFontOutlineSize = '0'; // Default: 0 (px)
  $nowShowingBottomFontOutlineColor = '#FFFFFF'; // Default: #FFFFFF (White)
  $nowShowingBottomFontEnabled = ''; // Default: FALSE
  $nowShowingBottomFontID = 'None'; // Default: None
  $nowShowingBottomAutoScale = ''; // Default: FALSE
  $nowShowingBottomScroll = 'Disabled'; // Default: Disabled

  // Misc Configuration
  $pmpDisplayClock = 'Disabled'; // Default: Disabled (FUTURE)
  // $pmpBottomScroll = ''; // Default: Disabled
  $pmpBottomScrollSpeed = '1'; // Default: 1 (FUTURE)
?>

**Comment by TATUMTOT** [comment]
I only have 2 logs 

getCachedfile.log

24hr Cache Clear: cache/posters/
24hr Cache Clear: cache/art/

getMedianURL.log

Plex Session URL: https://10-0-5-100.ASDF.plex.direct:32400:32400/status/sessions?X-Plex-Token=ABCD
Session URL: https://10-0-5-100.ASDF.plex.direct:32400:32400/status/sessions?X-Plex-Token=ABCD

DNS/TOKEN SANITIZED.

**Comment by TATUMTOT** [comment]
Here is the Full Config.

https://pastebin.pl/view/a46624c4

**Comment by ZeroCoolGOS** [comment]
Thanks for the config. I will try and see if I can reproduce the issue this week.

**Comment by TATUMTOT** [comment]
Also the Login does not look like the examples. the app shows 2.13.0. 




![image](https://user-images.githubusercontent.com/11933561/131525762-ea8d63b2-4c96-491b-bd4a-fb9874313ee8.png)

**Comment by TATUMTOT** [comment]
Here is the Data when Trying to use the command above from the original Commenter. 

 
PHP Warning:  include(/assets/plexmovieposter/tools.php): failed to open stream: No such file or directory in /var/www/html/assets/plexmovieposter/getPoster.php on line 3
PHP Warning:  include(): Failed opening '/assets/plexmovieposter/tools.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/assets/plexmovieposter/getPoster.php on line 3
PHP Warning:  file_put_contents(/var/www/html/cache/logs/getCacheFile.log): failed to open stream: Permission denied in /var/www/html/assets/plexmovieposter/tools.php on line 75
PHP Warning:  file_put_contents(/var/www/html/cache/logs/getCacheFile.log): failed to open stream: Permission denied in /var/www/html/assets/plexmovieposter/tools.php on line 75
PHP Warning:  file_put_contents(/var/www/html/cache/logs/getMediaURL.log): failed to open stream: Permission denied in /var/www/html/assets/plexmovieposter/tools.php on line 75
PHP Warning:  file_put_contents(/var/www/html/cache/logs/getMediaURL.log): failed to open stream: Permission denied in /var/www/html/assets/plexmovieposter/tools.php on line 75
PHP Warning:  file_get_contents(): Failed to enable crypto in /var/www/html/getData.php on line 34
PHP Warning:  file_get_contents(https://10-0-5-100.ABCD.plex.direct:32400:32400/status/sessions?X-Plex-Token=ABCD): failed to open stream: operation failed in /var/www/html/getData.php on line 34
Creating: cache/posters/ <br>Debug (GeneralCache_Prep): cache/posters/ <br>Creating: cache/art/ <br>Debug (GeneralCache_Prep): cache/art/ <br>Creating: cache/custom/ <br>Debug (GeneralCache_Prep): cache/custom/ <br>Creating: cache/fonts/ <br>Debug (GeneralCache_Prep): cache/fonts/ <br>Creating: cache/logs/ <br>Debug

**Comment by ZeroCoolGOS** [comment]
> Also the Login does not look like the examples. the app shows 2.13.0. 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/11933561/131525762-ea8d63b2-4c96-491b-bd4a-fb9874313ee8.png)
> 
> 

Thank you for bringing up the screenshot difference.  I have created a new issue to address the outdated images.

**Comment by ZeroCoolGOS** [comment]
> Here is the Data when Trying to use the command above from the original Commenter. 
> 
> 
> 
>  
> 
> PHP Warning:  include(/assets/plexmovieposter/tools.php): failed to open stream: No such file or directory in /var/www/html/assets/plexmovieposter/getPoster.php on line 3
> 
> PHP Warning:  include(): Failed opening '/assets/plexmovieposter/tools.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/assets/plexmovieposter/getPoster.php on line 3
> 
> PHP Warning:  file_put_contents(/var/www/html/cache/logs/getCacheFile.log): failed to open stream: Permission denied in /var/www/html/assets/plexmovieposter/tools.php on line 75
> 
> PHP Warning:  file_put_contents(/var/www/html/cache/logs/getCacheFile.log): failed to open stream: Permission denied in /var/www/html/assets/plexmovieposter/tools.php on line 75
> 
> PHP Warning:  file_put_contents(/var/www/html/cache/logs/getMediaURL.log): failed to open stream: Permission denied in /var/www/html/assets/plexmovieposter/tools.php on line 75
> 
> PHP Warning:  file_put_contents(/var/www/html/cache/logs/getMediaURL.log): failed to open stream: Permission denied in /var/www/html/assets/plexmovieposter/tools.php on line 75
> 
> PHP Warning:  file_get_contents(): Failed to enable crypto in /var/www/html/getData.php on line 34
> 
> PHP Warning:  file_get_contents(https://10-0-5-100.ABCD.plex.direct:32400:32400/status/sessions?X-Plex-Token=ABCD): failed to open stream: operation failed in /var/www/html/getData.php on line 34
> 
> Creating: cache/posters/ <br>Debug (GeneralCache_Prep): cache/posters/ <br>Creating: cache/art/ <br>Debug (GeneralCache_Prep): cache/art/ <br>Creating: cache/custom/ <br>Debug (GeneralCache_Prep): cache/custom/ <br>Creating: cache/fonts/ <br>Debug (GeneralCache_Prep): cache/fonts/ <br>Creating: cache/logs/ <br>Debug 
> 
> 

Interesting.  Since all my development and running has always been in a docker image I have not ran it directly on a none fresh image.

I will also attempt that as part of my testing this week.  And try to recreate the issues you are having so we can get a fix out.

**Comment by TATUMTOT** [comment]
THANK YOU SO MUCH!!

**Comment by ZeroCoolGOS** [comment]
I am trying to do an install on a "dirty" Pi Zero to see if I can recreate some of the issues that have been reported.

@TATUMTOT I have taken your config and applied it to my working system and its working fine, so I don't believe its a config file issue.

Has anyone tried to hit the PI's IP address to see if its displaying the poster remotely?

**Comment by TATUMTOT** [comment]
Yes I have tried that I get a blank page unless I'm going to the config page.

**Comment by TATUMTOT** [comment]
Black page!

**Comment by TATUMTOT** [comment]
![image](https://user-images.githubusercontent.com/11933561/132267911-dcfc5157-92cc-4f14-9374-af700e26f815.png)

**Comment by TATUMTOT** [comment]
![image](https://user-images.githubusercontent.com/11933561/132267952-f4c222e2-c383-4680-bf1a-d3ee4a270290.png)

**Comment by TATUMTOT** [comment]
@ZeroCoolGOS do we have an update. Or what can I do?

**Comment by ZeroCoolGOS** [comment]
@TATUMTOT 

Sorry I not have any work around for you as of yet.  I have not been able to recreate the issue yet.  I still have more testing to do.  But was able to get installed on a dirty system with still no issue.

**Comment by TATUMTOT** [comment]
@ZeroCoolGOS what base os are you running? Also I'm willing to do a remote session and get you connected so you can see my side.

**Comment by ZeroCoolGOS** [comment]
@TATUMTOT I have been running on raspian on bare metal and Debian in the docker image.

Let me do a bit more testing and then we could also look at a remote session sometime to try and figure it out.

**Comment by Jacksaur** [comment]
I cannibalized the SD card from my Pi for another project temporarily, but if it helps, I can reinstall and see if the problem still occurs for me too, if you think that may help.

**Comment by TATUMTOT** [comment]
I'm was going to try the full os vs just the desktop version just incase we are missing something.

**Comment by TATUMTOT** [comment]
Ok I have fully reinstalled and stated over Following the Guide. We still have the issue But I went through all settings. I was able to get the Custom Image and text to display. So now that leads me back down the path of a connection issue to Plex. 

Here is the basic modifications. That I have done.
Non Standard Public port.
Custom token was generated for this APP
Encryption is Required 
Strict TLS is required 

I can tell that token was used based on the New Device Email.

I have tested this on another Server that is Basic Install and it does not work on that one either.

But I believe the issues is Between Server to the Plex Server and not on the rendering side. This could be a Permissions thing also but I have ran the Chmod to make those modifications and logs are being created and I was able to upload a custom image to the DIR.

@ZeroCoolGOS

**Comment by ZeroCoolGOS** [comment]
@TATUMTOT 
What do you mean "Custom token was generated for this APP"?

The token should be from your Plex server and would have only been generated on Plex installation. 

Also is your Plex and your Poster system on the same network?

**Comment by TATUMTOT** [comment]
Custom token = https://gist.github.com/fleXible/709e4583086b926646cb5304361693b4

Plex Server is not on the same local network. It is on another Subnet but has Full access and nothing is restricting Traffic the to the 2 Subnets. 
The Second Test Plex Server is on the Same Subnet Though.

@ZeroCoolGOS

**Comment by ZeroCoolGOS** [comment]
> Custom token = https://gist.github.com/fleXible/709e4583086b926646cb5304361693b4
> 
> 
> 
> Plex Server is not on the same local network. It is on another Subnet but has Full access and nothing is restricting Traffic the to the 2 Subnets. 
> 
> The Second Test Plex Server is on the Same Subnet Though.
> 
> 
> 
> @ZeroCoolGOS 

That would not be the correct token. 

It should be a 20 (or so) AlphaNumeric string.

**Comment by ZeroCoolGOS** [comment]
@TATUMTOT 

https://github.com/MattsShack/Plex-Movie-Poster-Display/blob/dev/docs/PlexData.md

see finding the token in this doc.

**Comment by TATUMTOT** [comment]
@ZeroCoolGOS Yep Same thing Just not a Shared Token like when you take it out of your Browser windows like in the documentation. 


This is how I have all third Party integrations configured. I have never had a problem.

**Comment by TATUMTOT** [comment]
@ZeroCoolGOS 
![IMG_0459](https://user-images.githubusercontent.com/11933561/133214613-ad20c69a-b9c0-4432-94f8-2a70e047832d.jpg)

**Comment by ZeroCoolGOS** [comment]
@TATUMTOT 

No.  Sorry.  This system is not a registered component of plex and needs the token from plex.  There is no integration into plex its a read only project.  So you need the plex token not a generated token.

**Comment by ZeroCoolGOS** [comment]
There is no "Authorized Device" required.

**Comment by TATUMTOT** [comment]
I have tried it with Both Still have the same issues.

**Comment by ZeroCoolGOS** [comment]
Hmm. 

If the setup was followed based on the documentation then it should work fine.  So at this point I am stumped.  I have not had many issues when I setup a new system, but I have gone through the installs many times.  I will also look at trying to simulate the setup you have done as well to see if I can reproduce.

@MattsShack maybe you can jump in and try and help us find the root issue.

I will also work on trying to add more diag information to the logs to help us route out the issue.

@TATUMTOT sorry we have not been able to get this sorted out for you yet.

**Comment by TATUMTOT** [comment]
@ZeroCoolGOS @MattsShack 

I understand I think the next steps could be a remote session. 
Do you have a raspberry pi ?

It is late here so i will check back on this threat tomorrow

**Comment by ZeroCoolGOS** [comment]
@TATUMTOT 

Yes I have a Raspberry Pi.

Where are you based?  I am on the West Coast.

**Comment by TATUMTOT** [comment]
@ZeroCoolGOS East Cost. So we can try this tomorrow if you have time? Just a little earlier for me LOL.

**Comment by TATUMTOT** [comment]
@ZeroCoolGOS want to get on a remote session?

**Comment by ZeroCoolGOS** [comment]
@TATUMTOT 
We can try and do a quick remote session to see if we can get you sorted.

**Comment by TATUMTOT** [comment]
@ZeroCoolGOS ok let's do it

**Comment by ZeroCoolGOS** [comment]
@TATUMTOT 
How do we want to do a remote session?

**Comment by TATUMTOT** [comment]
@ZeroCoolGOS 
Michael Tatum is inviting you to a scheduled Zoom meeting.

Topic: Tatum's Personal Meeting Room

Join Zoom Meeting
https://us02web.zoom.us/j/5793781780?pwd=NlZ4akNzN1lXQ3hQSWk5UWkwQnF2UT09

Meeting ID: 579 378 1780
Passcode: 123
One tap mobile
+19292056099,,5793781780# US (New York)
+13017158592,,5793781780# US (Washington DC)

Dial by your location
        +1 929 205 6099 US (New York)
        +1 301 715 8592 US (Washington DC)
        +1 312 626 6799 US (Chicago)
        +1 669 900 6833 US (San Jose)
        +1 253 215 8782 US (Tacoma)
        +1 346 248 7799 US (Houston)
Meeting ID: 579 378 1780
Find your local number: https://us02web.zoom.us/u/kbYNDtarqw

**Comment by ZeroCoolGOS** [comment]
Root Cause was around secure SSL not connecting to PLEX when plex is set to use Secure connection only.

Zoom Call Notes - RAW (will come back and refine the findings):
Setting Plex as secure only does not connect (Network/Secure Connections: Required)
Expand field length for IP and Secure IP by 5
Add a field for PORT when not using secure
If in secure "https://" purge.

Fix documentation for True/False as O/1

Note: Look at how to register app in plex to use our own dedicated token.
Cookie to have show/hide advanced.

Post Warning if Refresh is below 10s, could crash plex

Testing:
Try different WebServices and possible run on Windows/MacOS and install documents?
Support Apache?

Test TV metadata for Now Showing and Coming Soon

Make diag  pages more accessible - Add Diag Tab.

**Comment by TATUMTOT** [comment]
@ZeroCoolGOS Token request. 

https://forums.plex.tv/t/how-to-request-a-x-plex-token-token-for-your-app/84551

**Comment by ZeroCoolGOS** [comment]
@Jacksaur 
This was your original issue that you reported and @1upmushroom was also having the same issue.

Based on the work I have done with @TATUMTOT we did find that there was an issue with how the "Plex Server Direct address" functionality is working, and issues around non-standard port setting.

So here are a few questions and trouble shooting steps.
- Are you using the Plex SSL connection with the Plex Server Direct address?  
- If yes, in your Plex Settings (under network) do you have "Secure connections" set to Required?
- If yes, try to set "Secure connections" to "Preferred" and see if that resolves your issue.

- Are you using a non-standard port for your Plex server you are trying to connect to?
- If yes, manually edit the configuration file and add the port that you are using.

Please let us know if any of these help or if none of them apply to you.

There are now a few tickets created to address the above issues, as well as some work will go into more diagnostics for better identifying issues in the future.

Sorry for the late reply.

**Comment by TATUMTOT** [comment]
Only Do this for Testing!

I already had STunnel Configured for my magic mirror projects 

I have I have confirmed that everything works with HTTP but not with HTTPS. Unsure why but for those who are also having this issues you can deploy Stunnel https://www.stunnel.org/.

Stunnel Config
[plex-MM-proxy]
client = yes
; IP address and the port you want to use for your PMDM. This is only to be used for PMDM not for Main Library Sharing or External Access.
accept = 192.168.1.50:32444
connect = 127.0.0.1:32400

**Comment by Jacksaur** [comment]
Regretably I still haven't got my Pi back up and running yet. I'll be sure to do it as soon as I can tomorrow and report back on the results.

Not sure about the first question, but my Secure Connections is already set to Preferred, and my Port is the default value. (32400 I believe?)

**Comment by Jacksaur** [comment]
Apologies for the delay, Evening shifts are a pain.
Reinstalled everything from scratch, and it's now all working perfectly! Didn't need to change any settings on my Server or the Pi itself.
Cheers.
