### ISSUE TITLE
New Plex Media Server Update Broke PMPD3

### ISSUE THREAD

**Issue by titelies** [MattsShack/Plex-Movie-Poster-Display#92]
Just updated my Plex Media Server to the most recent version Version 1.23.5.4862.
I no longer install BETA updates, this is a PMS release. [https://forums.plex.tv/t/plex-media-server/30447/448](url)
I just get a black screen on both my laptop and TV display now.
Not sure what happened. Hoping I can revert PMS to an older version, need to investigate how I can do that...

**Comment by bystand3r** [comment]
I think it broke most peoples plex server. If you experiencing DB is locked error in logs revert to old version. Devs working on patching issue.


Sent from my iPhone

On 24 Jul 2021, at 8:46 am, titelies ***@***.***> wrote:

﻿

Just updated my Plex Media Server to the most recent version Version 1.23.5.4862.
I no longer install BETA updates, this is a PMS release. https://forums.plex.tv/t/plex-media-server/30447/448<url>
I just get a black screen on both my laptop and TV display now.
Not sure what happened. Hoping I can revert PMS to an older version, need to investigate how I can do that...

**Comment by titelies** [comment]
@bystand3r Thank you for the info. You were absolutely right, Plex has fixed the issue today on their end. All is well with PMPD3 and Tautulli
