### ISSUE TITLE
Quick fix = Remove invalid footer under plex configuration page

### ISSUE THREAD

**Issue by TATUMTOT** [MattsShack/Plex-Movie-Poster-Display#96]
We need to remove 

PLEX, PLEX PASS, myPLEX, PLEX MEDIA SERVER, PLEX MEDIA CENTER, PLEX MEDIA MANAGER, PLEX HOME THEATER, PLEX TV, PLEX.TV, the Plex Play Logo (">" in stylized format) are trademarks that are the exclusive property of Plex,

This should match all the other pages.

**Comment by ZeroCoolGOS** [comment]
@TATUMTOT 
This is on the Plex Server page?

If so then it was a decision that was made to place this footer as part of some requirements for PLEX especially as part of there usage of name.  This is also why we don't specify PLEX anywhere else within the settings.  Keeping it isolated.

If we where to add more media services then we would follow the same way.

**Comment by TATUMTOT** [comment]
Ok I can see that as a Legal Out. We should still fix (">" in stylized format)

**Comment by ZeroCoolGOS** [comment]
> Ok I can see that as a Legal Out. We should still fix (">" in stylized format)

That is part of there copywriter string, so it would also need to remain.

**Comment by TATUMTOT** [comment]
Ok
